#  |  |  ___ \    \  |         |
#  |  |     ) |  |\/ |   _  |  |  /   _ 
# ___ __|  __/   |   |  (   |    <    __/ 
#    _|  _____| _|  _| \__,_| _|\_\ \___|
#                              by jcluzet
################################################################################
#                                     CONFIG                                   #
################################################################################

NAME        := libftprintf.a
CC        := clang
FLAGS    := -Wall -Wextra -Werror 
################################################################################
#                                 PROGRAM'S SRCS                               #
################################################################################

SRCS        :=      	print_unsigned_int.c \
                          tests.c \
                          print_hexadecimal_helper.c \
                          print_int_helper.c \
                          print_pointer_helper.c \
                          print_hexadecimal.c \
                          print_int.c \
                          print_pointer.c \
                          libft_funcs/ft_itoa_unsigned.c \
                          libft_funcs/ft_max.c \
                          libft_funcs/ft_itoa_base.c \
                          libft_funcs/ft_numlen.c \
                          libft_funcs/ft_toupper.c \
                          libft_funcs/ft_putchar_fd.c \
                          libft_funcs/ft_strchr.c \
                          libft_funcs/ft_itoa.c \
                          libft_funcs/ft_putstr_fd.c \
                          libft_funcs/ft_memmove.c \
                          libft_funcs/ft_strlen.c \
                          libft_funcs/ft_isdigit.c \
                          libft_funcs/ft_memcmp.c \
                          libft_funcs/ft_atoi.c \
                          libft_funcs/ft_bzero.c \
                          libft_funcs/ft_numlen_base_unsigned.c \
                          libft_funcs/ft_memcpy.c \
                          libft_funcs/ft_strncmp.c \
                          determine_print_len.c \
                          ft_printf.c \
                          parse_conversion_specification.c \
                          print_char_and_str.c \
                          
OBJS        := $(SRCS:.c=.o)

.c.o:
	${CC} ${FLAGS} -c $< -o ${<:.c=.o}

################################################################################
#                                  Makefile  objs                              #
################################################################################


CLR_RMV		:= \033[0m
RED		    := \033[1;31m
GREEN		:= \033[1;32m
YELLOW		:= \033[1;33m
BLUE		:= \033[1;34m
CYAN 		:= \033[1;36m
RM		    := rm -f

${NAME}:	${OBJS}
			@echo "$(GREEN)Compilation ${CLR_RMV}of ${YELLOW}$(NAME) ${CLR_RMV}..."
			${CC} ${FLAGS} -o ${NAME} ${OBJS}
			@echo "$(GREEN)$(NAME) created[0m ✔️"

all:		${NAME}

bonus:		all

clean:
			@ ${RM} *.o */*.o */*/*.o
			@ echo "$(RED)Deleting $(CYAN)$(NAME) $(CLR_RMV)objs ✔️"

fclean:		clean
			@ ${RM} ${NAME}
			@ echo "$(RED)Deleting $(CYAN)$(NAME) $(CLR_RMV)binary ✔️"

re:			fclean all

.PHONY:		all clean fclean re


